my_api = [{"word":"beautiful","phonetic":"/ˈbjuːtɪfəl/","phonetics":[{"text":"/ˈbjuːtɪfəl/","audio":"https://api.dictionaryapi.dev/media/pronunciations/en/beautiful-uk.mp3","sourceUrl":"https://commons.wikimedia.org/w/index.php?curid=9014276","license":{"name":"BY 3.0 US","url":"https://creativecommons.org/licenses/by/3.0/us"}},{"text":"/ˈbjuːtɪfəl/","audio":"https://api.dictionaryapi.dev/media/pronunciations/en/beautiful-us.mp3","sourceUrl":"https://commons.wikimedia.org/w/index.php?curid=837183","license":{"name":"BY-SA 3.0","url":"https://creativecommons.org/licenses/by-sa/3.0"}}],"meanings":[{"partOfSpeech":"noun","definitions":[{"definition":"Someone who is beautiful. Can be used as a term of address.","synonyms":[],"antonyms":[],"example":"Hey, beautiful!"}],"synonyms":[],"antonyms":[]},{"partOfSpeech":"adjective","definitions":[{"definition":"Attractive and possessing beauty.","synonyms":[],"antonyms":[],"example":"Anyone who has ever met her thought she was absolutely beautiful."},{"definition":"(of the weather) Pleasant; clear.","synonyms":[],"antonyms":[],"example":"It's beautiful outside, let's go for a walk."},{"definition":"Well executed.","synonyms":[],"antonyms":[],"example":"The skater performed a beautiful axel."}],"synonyms":["bloody","damned","great","intensifier","just","marvellous","marvelous","nice","wonderful","clear","fine","nice","pleasant","sunny","attractive","beauteous","cute","fair","fit","good-looking","gorgeous","handsome","hot","lovely","nice-looking","pretty","shapely","sheen","excellent","exceptional","good","great","marvellous","marvelous","perfect","stylish","wonderful"],"antonyms":["bad","cloudy","dull","miserable","overcast","rainy","wet","grotesque","hideous","homely","misshapen","plain","repulsive","ugly","unbeautiful","average","bad","mediocre","poor","shoddy","substandard","terrible","weak"]}],"license":{"name":"CC BY-SA 3.0","url":"https://creativecommons.org/licenses/by-sa/3.0"},"sourceUrls":["https://en.wiktionary.org/wiki/beautiful"]}]

# dictionary_first_element = beautiful[0]
# word = dictionary_first_element.get('word')
# phonetic = dictionary_first_element.get('phonetic')
# print(word, phonetic)
# print(f"{word} words's phonetics is {phonetic} " )

synonyms = my_api[0].get('meanings')[1].get('synonyms')
for e in synonyms:
    print(e)